// Auto-generated by scripts/generate-data.mjs — DO NOT EDIT
// Generated at: 2026-06-04T07:35:15.986Z

import type { ArticleMeta, NoteMeta, GardenNoteMeta, JourneyNodeMeta, Album, ImageInfo, Friend, ContentComment, GuestbookMessage } from "@/types";

// ─── Articles ───────────────────────────────────────────────────────
export const articles: ArticleMeta[] = [
  {
    "slug": "welcome",
    "title": "欢迎来到我的个人网站",
    "date": "2026-05-28",
    "description": "这是网站的第一篇文章，简单介绍一下这个空间。",
    "coverImage": "https://raw.githubusercontent.com/Nofear0304/image/master/photo/屏幕截图 2026-06-02 183152.png",
    "tags": [
      "生活",
      "介绍"
    ],
    "readingTime": 1,
    "likes": 0
  }
];

export const articleRawContents: Record<string, string> = {
  "welcome": "\n## 你好，欢迎来访 👋\n\n这是一个属于我自己的小小数字空间。在这里我会分享：\n\n- **文章**：技术思考、生活感悟、读书笔记\n- **照片**：日常摄影、旅行记录、随手拍\n\n### 关于这个网站\n\n这个网站用 **Next.js** 构建，文章用 Markdown 写作，设计追求简约大气。\n\n没有评论、没有算法推荐、没有社交压力——只是一个安静的个人角落。\n\n### 联系方式\n\n如果你想联系我，可以通过以下方式：\n\n- Email: hello@example.com\n- GitHub: [github.com/yourname](https://github.com)\n\n---\n\n*感谢来访，希望你喜欢这里。*\n"
};

export const articleHtmlContents: Record<string, string> = {
  "welcome": "<h2>你好，欢迎来访 👋</h2>\n<p>这是一个属于我自己的小小数字空间。在这里我会分享：</p>\n<ul>\n<li><strong>文章</strong>：技术思考、生活感悟、读书笔记</li>\n<li><strong>照片</strong>：日常摄影、旅行记录、随手拍</li>\n</ul>\n<h3>关于这个网站</h3>\n<p>这个网站用 <strong>Next.js</strong> 构建，文章用 Markdown 写作，设计追求简约大气。</p>\n<p>没有评论、没有算法推荐、没有社交压力——只是一个安静的个人角落。</p>\n<h3>联系方式</h3>\n<p>如果你想联系我，可以通过以下方式：</p>\n<ul>\n<li>Email: hello@example.com</li>\n<li>GitHub: <a href=\"https://github.com\">github.com/yourname</a></li>\n</ul>\n<hr>\n<p><em>感谢来访，希望你喜欢这里。</em></p>\n"
};

// ─── Notes ─────────────────────────────────────────────────────────
export const notes: NoteMeta[] = [
  {
    "slug": "first",
    "title": "网站搭建第一天",
    "date": "2026-06-02",
    "description": "正在逐步完善功能",
    "tags": [
      "网站",
      "开发"
    ],
    "readingTime": 1,
    "likes": 0
  },
  {
    "slug": "code-refactoring",
    "title": "周末的代码重构感悟",
    "date": "2026-05-20",
    "description": "重构不是为了完美，而是为了让代码更易于理解和维护。",
    "tags": [
      "技术",
      "成长"
    ],
    "readingTime": 1,
    "likes": 12
  },
  {
    "slug": "photography-life",
    "title": "摄影与生活",
    "date": "2026-04-15",
    "description": "透过镜头，我看到了不一样的世界。",
    "tags": [
      "摄影",
      "生活"
    ],
    "readingTime": 1,
    "likes": 8
  }
];

export const noteRawContents: Record<string, string> = {
  "code-refactoring": "\n## 为什么要重构\n\n重构是软件开发中不可或缺的一环。当代码变得难以理解、难以扩展时，就是重构的信号。\n\n### 我的重构原则\n\n1. **先写测试，再重构** — 确保行为不变\n2. **小步前进** — 每次只改一点，持续集成\n3. **关注可读性** — 代码是写给人看的\n\n## 这次重构的收获\n\n花了整个周末重构了一个老模块，虽然功能上没有变化，但代码清晰了很多。重构就像是给代码做一次深度清洁，虽然过程辛苦，但结果让人愉悦。\n\n> 好的代码本身就是最好的文档。\n",
  "first": "\n## 网站搭建第一天\n\n正在逐步完善功能。\n",
  "photography-life": "\n## 我与摄影\n\n摄影让我学会了观察。在按下快门的瞬间，你需要考虑光线、构图、情绪。\n\n### 我的器材\n\n- Sony A7M4\n- 24-70mm f/2.8\n- 85mm f/1.4\n\n### 拍摄心得\n\n最好的相机就是你手中的那台。器材只是工具，真正重要的是你的眼睛和心。\n\n街拍是我最喜欢的题材，因为最真实、最有故事感。\n"
};

export const noteHtmlContents: Record<string, string> = {
  "code-refactoring": "<h2>为什么要重构</h2>\n<p>重构是软件开发中不可或缺的一环。当代码变得难以理解、难以扩展时，就是重构的信号。</p>\n<h3>我的重构原则</h3>\n<ol>\n<li><strong>先写测试，再重构</strong> — 确保行为不变</li>\n<li><strong>小步前进</strong> — 每次只改一点，持续集成</li>\n<li><strong>关注可读性</strong> — 代码是写给人看的</li>\n</ol>\n<h2>这次重构的收获</h2>\n<p>花了整个周末重构了一个老模块，虽然功能上没有变化，但代码清晰了很多。重构就像是给代码做一次深度清洁，虽然过程辛苦，但结果让人愉悦。</p>\n<blockquote>\n<p>好的代码本身就是最好的文档。</p>\n</blockquote>\n",
  "first": "<h2>网站搭建第一天</h2>\n<p>正在逐步完善功能。</p>\n",
  "photography-life": "<h2>我与摄影</h2>\n<p>摄影让我学会了观察。在按下快门的瞬间，你需要考虑光线、构图、情绪。</p>\n<h3>我的器材</h3>\n<ul>\n<li>Sony A7M4</li>\n<li>24-70mm f/2.8</li>\n<li>85mm f/1.4</li>\n</ul>\n<h3>拍摄心得</h3>\n<p>最好的相机就是你手中的那台。器材只是工具，真正重要的是你的眼睛和心。</p>\n<p>街拍是我最喜欢的题材，因为最真实、最有故事感。</p>\n"
};

// ─── Garden ────────────────────────────────────────────────────────
export const gardenNotes: GardenNoteMeta[] = [
  {
    "slug": "react-state",
    "title": "React 状态管理方案比较",
    "date": "2026-03-15",
    "updated": "2026-05-28",
    "tags": [
      "React",
      "State",
      "Frontend",
      "Architecture"
    ],
    "links": [
      "react-hooks-deep"
    ],
    "status": "evergreen",
    "excerpt": "从最早的 setState 到现在的 Server Components，React 状态管理经历了巨大的变化。  方案  适用场景  学习成本"
  },
  {
    "slug": "react-hooks-deep",
    "title": "深入理解 React Hooks",
    "date": "2026-02-10",
    "updated": "2026-04-20",
    "tags": [
      "React",
      "Hooks",
      "Frontend"
    ],
    "links": [
      "react-state"
    ],
    "status": "budding",
    "excerpt": "Hooks 不是魔法，它们是利用闭包和链表实现的普通 JavaScript 函数。  触发重渲染的机制"
  }
];

export const gardenNoteRawContents: Record<string, string> = {
  "react-hooks-deep": "\n## Hooks 的本质\n\nHooks 不是魔法，它们是利用闭包和链表实现的普通 JavaScript 函数。\n\n### 关键 Hooks 深入\n\n#### useState\n- 触发重渲染的机制\n- 批量更新（batching）\n- 函数式更新的使用场景\n\n#### useEffect\n- 清理函数的重要性\n- 依赖数组的陷阱\n- 与生命周期的心智模型差异\n\n#### useRef\n- 不只是 DOM 引用\n- 保存可变值而不触发渲染\n- 与 useState 的选择\n\n### 自定义 Hooks 模式\n\n封装可复用的状态逻辑，保持组件简洁。\n",
  "react-state": "\n## React 状态管理的演进\n\n从最早的 `setState` 到现在的 Server Components，React 状态管理经历了巨大的变化。\n\n### 方案对比\n\n| 方案 | 适用场景 | 学习成本 |\n|------|---------|---------|\n| useState + useContext | 小型应用 | 低 |\n| Zustand | 中型应用 | 低 |\n| Jotai | 原子化状态 | 中 |\n| Redux Toolkit | 大型应用 | 高 |\n\n### 我的选择\n\n对于大多数项目，**Zustand** 是最佳平衡点——足够简单，又足够强大。\n\n### 核心原则\n\n1. 状态尽量靠近使用它的组件\n2. 避免过早抽象\n3. 派生状态优于冗余状态\n"
};

export const gardenNoteHtmlContents: Record<string, string> = {
  "react-hooks-deep": "<h2>Hooks 的本质</h2>\n<p>Hooks 不是魔法，它们是利用闭包和链表实现的普通 JavaScript 函数。</p>\n<h3>关键 Hooks 深入</h3>\n<h4>useState</h4>\n<ul>\n<li>触发重渲染的机制</li>\n<li>批量更新（batching）</li>\n<li>函数式更新的使用场景</li>\n</ul>\n<h4>useEffect</h4>\n<ul>\n<li>清理函数的重要性</li>\n<li>依赖数组的陷阱</li>\n<li>与生命周期的心智模型差异</li>\n</ul>\n<h4>useRef</h4>\n<ul>\n<li>不只是 DOM 引用</li>\n<li>保存可变值而不触发渲染</li>\n<li>与 useState 的选择</li>\n</ul>\n<h3>自定义 Hooks 模式</h3>\n<p>封装可复用的状态逻辑，保持组件简洁。</p>\n",
  "react-state": "<h2>React 状态管理的演进</h2>\n<p>从最早的 <code>setState</code> 到现在的 Server Components，React 状态管理经历了巨大的变化。</p>\n<h3>方案对比</h3>\n<p>| 方案 | 适用场景 | 学习成本 |\n|------|---------|---------|\n| useState + useContext | 小型应用 | 低 |\n| Zustand | 中型应用 | 低 |\n| Jotai | 原子化状态 | 中 |\n| Redux Toolkit | 大型应用 | 高 |</p>\n<h3>我的选择</h3>\n<p>对于大多数项目，<strong>Zustand</strong> 是最佳平衡点——足够简单，又足够强大。</p>\n<h3>核心原则</h3>\n<ol>\n<li>状态尽量靠近使用它的组件</li>\n<li>避免过早抽象</li>\n<li>派生状态优于冗余状态</li>\n</ol>\n"
};

// ─── Journey ───────────────────────────────────────────────────────
export const journeyNodes: JourneyNodeMeta[] = [
  {
    "slug": "childhood",
    "title": "童年",
    "period": "2011 - 2016",
    "coverImage": "https://raw.githubusercontent.com/Nofear0304/image/master/photo/9494410e96114a921446a3699c2acf87.png",
    "summary": "在小城镇长大的童年时光，对世界充满好奇，喜欢拆解玩具、观察自然，埋下了探索未知的种子。",
    "phase": "childhood",
    "tags": [
      "童年",
      "好奇心",
      "探索"
    ],
    "order": 0
  },
  {
    "slug": "middle-school",
    "title": "初中",
    "period": "2016 - 2019",
    "coverImage": "https://raw.githubusercontent.com/Nofear0304/image/master/photo/2c695c1456c3c704d454b549bae371f6.jpg",
    "summary": "从小学升入初中，开始接触更多学科知识，在数学和物理中找到了热爱，第一次写下了自己的代码。",
    "phase": "middle-school",
    "tags": [
      "初中",
      "数学",
      "编程入门"
    ],
    "order": 1
  },
  {
    "slug": "high-school",
    "title": "高中",
    "period": "2019 - 2022",
    "coverImage": "https://raw.githubusercontent.com/Nofear0304/image/master/photo/c83d37d22501c89e2f6f30de16f1ca11.jpg",
    "summary": "考入重点高中，在激烈的竞争中磨砺自我，系统学习编程，参加了信息学竞赛，明确了未来方向。",
    "phase": "high-school",
    "tags": [
      "高中",
      "信息学竞赛",
      "编程"
    ],
    "order": 2
  },
  {
    "slug": "college",
    "title": "大学",
    "period": "2022 - 2025",
    "coverImage": "https://raw.githubusercontent.com/Nofear0304/image/master/photo/fdfa938969631574d0d5addd59b66739.jpg",
    "summary": "四年计算机专业学习，从编程小白到 ACM 竞赛获奖，奠定了技术基础。",
    "phase": "college",
    "tags": [
      "大学",
      "计算机",
      "ACM",
      "算法"
    ],
    "order": 3
  },
  {
    "slug": "first-job",
    "title": "工作",
    "period": "2026 - 未来",
    "summary": "从校园到职场的转变，在前端开发岗位上持续成长。",
    "phase": "career",
    "tags": [
      "职场",
      "前端",
      "成长",
      "全栈"
    ],
    "order": 4
  },
  {
    "slug": "life",
    "title": "生活",
    "period": "daily",
    "coverImage": "https://raw.githubusercontent.com/Nofear0304/image/master/photo/72c599a89f1598c50613f8ccded7db0e.png",
    "summary": "工作之外的生活同样精彩——阅读、摄影、旅行、思考，在平凡日常中寻找不平凡的意义。",
    "phase": "life",
    "tags": [
      "生活",
      "爱好",
      "阅读",
      "摄影",
      "旅行"
    ],
    "order": 5
  }
];

export const journeyNodeRawContents: Record<string, string> = {
  "childhood": "\n## 童年记忆\n\n我的童年在南方一座小城度过。那时候最快乐的事，就是在周末跟着父母去新华书店，一待就是一下午。科普读物、百科全书、漫画杂志——什么都看，什么都好奇。\n\n家里第一台电脑是二年级时父亲买的。虽然那时候只会玩扫雷和纸牌，但那个会发光的屏幕就像一个通往另一个世界的窗口。从那以后，我对\"这个东西是怎么工作的\"产生了浓厚的兴趣。\n",
  "college": "\n## 大学四年的技术成长\n\n从大一第一次接触 C 语言的迷茫，到大四能够独立完成全栈项目的自信，这四年见证了一个程序员的诞生。\n\n### 学习路径\n\n1. **大一**：C 语言 → 数据结构 → 面向对象编程\n2. **大二**：算法竞赛训练 → Java/ Python → 数据库\n3. **大三**：Web 开发 → React 生态 → 操作系统/网络\n4. **大四**：实习经验 → 毕设项目 → 职业规划\n\n### 竞赛经历\n\nACM 集训队的训练是大学最难忘的经历之一。每周至少 3 次训练赛，刷了上千道题，从一个只能做水题的小白成长为能够独当一面的队员。\n",
  "first-job": "\n## 职场第一年\n\n从学生到工程师的身份转变，不仅是技术栈的扩展，更是思维方式的重塑。\n\n### 技术成长\n\n- React / Next.js 从会用 → 理解原理\n- TypeScript 从了解到必备\n- 从纯前端到全栈的跨越\n- 工程化思维的建立\n\n### 软技能\n\n- 跨部门沟通协作\n- 需求分析与技术方案设计\n- 时间管理与优先级排序\n",
  "high-school": "\n## 高中：奋斗与抉择\n\n高中是人生中第一个真正意义上的\"分水岭\"。进入重点高中后，身边的每一个同学都非常优秀，这种环境既是压力也是动力。\n\n最幸运的是遇到了信息学竞赛这个契机。在竞赛教练的指导下，我开始系统地学习算法和数据结构。那些挑灯夜战刷题的日子虽然辛苦，但每次 AC 一道难题时的成就感，足以抵消所有的疲惫。\n\n这段经历让我明白了两个道理：一是兴趣是最好的老师，二是系统性的刻意练习是提升能力的最有效途径。这两个认知一直陪伴我走到今天。\n",
  "life": "\n## 生活中的我\n\n工作只是人生的一部分。在代码之外，我努力让每一天都过得充实而有意义。\n\n### 阅读\n\n书籍是我最好的朋友。从技术书籍到人文社科，从科幻小说到哲学随笔——阅读让我看到更大的世界，也让我在忙碌的工作之余保持思考的习惯。\n\n> \"读一本好书，就是和许多高尚的人谈话。\" —— 歌德\n\n### 摄影\n\n摄影教会我观察。那些容易被忽略的光影、色彩、表情，在镜头下都变得珍贵。我不追求器材，只追求那一刻的感动。\n\n### 旅行\n\n世界很大，想去的地方很多。每一次旅行都是一次自我更新——在陌生的街头迷路，在不知名的咖啡馆发呆，在山顶等一场日出。这些经历让生活有了更多的层次和色彩。\n\n### 日常\n\n认真做一顿饭，整理一下房间，给朋友发一条消息——生活中的小确幸往往藏在最平凡的细节里。学会感受当下，是我一直在练习的事情。\n\n> 生活不在别处，就在此时此刻 ✨\n",
  "middle-school": "\n## 初中：探索与觉醒\n\n初中三年是人生中非常重要的转折期。从小学的被动学习，逐渐转变为主动探索。数学课上那些精妙的证明和推导让我着迷——原来世界上还有这样一种纯粹的美。\n\n信息技术课更是打开了新世界的大门。虽然当时学的 VB 在现在看来很\"古老\"，但那行 `MsgBox \"Hello, World!\"` 弹出的对话框，至今记忆犹新。那种\"我写了一段代码，电脑就按照我的想法行动了\"的体验，让我第一次感受到了编程的魅力。\n"
};

export const journeyNodeHtmlContents: Record<string, string> = {
  "childhood": "<h2>童年记忆</h2>\n<p>我的童年在南方一座小城度过。那时候最快乐的事，就是在周末跟着父母去新华书店，一待就是一下午。科普读物、百科全书、漫画杂志——什么都看，什么都好奇。</p>\n<p>家里第一台电脑是二年级时父亲买的。虽然那时候只会玩扫雷和纸牌，但那个会发光的屏幕就像一个通往另一个世界的窗口。从那以后，我对\"这个东西是怎么工作的\"产生了浓厚的兴趣。</p>\n",
  "college": "<h2>大学四年的技术成长</h2>\n<p>从大一第一次接触 C 语言的迷茫，到大四能够独立完成全栈项目的自信，这四年见证了一个程序员的诞生。</p>\n<h3>学习路径</h3>\n<ol>\n<li><strong>大一</strong>：C 语言 → 数据结构 → 面向对象编程</li>\n<li><strong>大二</strong>：算法竞赛训练 → Java/ Python → 数据库</li>\n<li><strong>大三</strong>：Web 开发 → React 生态 → 操作系统/网络</li>\n<li><strong>大四</strong>：实习经验 → 毕设项目 → 职业规划</li>\n</ol>\n<h3>竞赛经历</h3>\n<p>ACM 集训队的训练是大学最难忘的经历之一。每周至少 3 次训练赛，刷了上千道题，从一个只能做水题的小白成长为能够独当一面的队员。</p>\n",
  "first-job": "<h2>职场第一年</h2>\n<p>从学生到工程师的身份转变，不仅是技术栈的扩展，更是思维方式的重塑。</p>\n<h3>技术成长</h3>\n<ul>\n<li>React / Next.js 从会用 → 理解原理</li>\n<li>TypeScript 从了解到必备</li>\n<li>从纯前端到全栈的跨越</li>\n<li>工程化思维的建立</li>\n</ul>\n<h3>软技能</h3>\n<ul>\n<li>跨部门沟通协作</li>\n<li>需求分析与技术方案设计</li>\n<li>时间管理与优先级排序</li>\n</ul>\n",
  "high-school": "<h2>高中：奋斗与抉择</h2>\n<p>高中是人生中第一个真正意义上的\"分水岭\"。进入重点高中后，身边的每一个同学都非常优秀，这种环境既是压力也是动力。</p>\n<p>最幸运的是遇到了信息学竞赛这个契机。在竞赛教练的指导下，我开始系统地学习算法和数据结构。那些挑灯夜战刷题的日子虽然辛苦，但每次 AC 一道难题时的成就感，足以抵消所有的疲惫。</p>\n<p>这段经历让我明白了两个道理：一是兴趣是最好的老师，二是系统性的刻意练习是提升能力的最有效途径。这两个认知一直陪伴我走到今天。</p>\n",
  "life": "<h2>生活中的我</h2>\n<p>工作只是人生的一部分。在代码之外，我努力让每一天都过得充实而有意义。</p>\n<h3>阅读</h3>\n<p>书籍是我最好的朋友。从技术书籍到人文社科，从科幻小说到哲学随笔——阅读让我看到更大的世界，也让我在忙碌的工作之余保持思考的习惯。</p>\n<blockquote>\n<p>\"读一本好书，就是和许多高尚的人谈话。\" —— 歌德</p>\n</blockquote>\n<h3>摄影</h3>\n<p>摄影教会我观察。那些容易被忽略的光影、色彩、表情，在镜头下都变得珍贵。我不追求器材，只追求那一刻的感动。</p>\n<h3>旅行</h3>\n<p>世界很大，想去的地方很多。每一次旅行都是一次自我更新——在陌生的街头迷路，在不知名的咖啡馆发呆，在山顶等一场日出。这些经历让生活有了更多的层次和色彩。</p>\n<h3>日常</h3>\n<p>认真做一顿饭，整理一下房间，给朋友发一条消息——生活中的小确幸往往藏在最平凡的细节里。学会感受当下，是我一直在练习的事情。</p>\n<blockquote>\n<p>生活不在别处，就在此时此刻 ✨</p>\n</blockquote>\n",
  "middle-school": "<h2>初中：探索与觉醒</h2>\n<p>初中三年是人生中非常重要的转折期。从小学的被动学习，逐渐转变为主动探索。数学课上那些精妙的证明和推导让我着迷——原来世界上还有这样一种纯粹的美。</p>\n<p>信息技术课更是打开了新世界的大门。虽然当时学的 VB 在现在看来很\"古老\"，但那行 <code>MsgBox \"Hello, World!\"</code> 弹出的对话框，至今记忆犹新。那种\"我写了一段代码，电脑就按照我的想法行动了\"的体验，让我第一次感受到了编程的魅力。</p>\n"
};

// ─── Gallery / Albums ──────────────────────────────────────────────
export const albums: Album[] = [
  {
    "slug": "campus",
    "title": "学校",
    "description": "校园生活的点滴记录",
    "coverImage": "/images/gallery/campus/cover.jpg",
    "imageCount": 9
  },
  {
    "slug": "travel",
    "title": "旅行",
    "description": "旅途中的风景与故事",
    "coverImage": "/images/gallery/travel/cover.jpg",
    "imageCount": 23
  },
  {
    "slug": "photography",
    "title": "摄影",
    "description": "精心拍摄的摄影作品",
    "coverImage": "/images/gallery/photography/cover.jpg",
    "imageCount": 20
  }
];

export const allImages: ImageInfo[] = [
  {
    "filename": "26a134dd517d9cfb19f13ed28a80b5e9.jpg",
    "url": "/images/gallery/photography/26a134dd517d9cfb19f13ed28a80b5e9.jpg",
    "size": 1355776,
    "uploadedAt": "2026-06-02T13:10:50.709Z",
    "category": "摄影"
  },
  {
    "filename": "cover.jpg",
    "url": "/images/gallery/photography/cover.jpg",
    "size": 9701982,
    "uploadedAt": "2026-06-02T13:09:26.748Z",
    "category": "摄影"
  },
  {
    "filename": "e69190f83b7b852e2d3fa98d2547e4a2.jpg",
    "url": "/images/gallery/photography/e69190f83b7b852e2d3fa98d2547e4a2.jpg",
    "size": 6171220,
    "uploadedAt": "2026-06-02T13:05:35.779Z",
    "category": "摄影"
  },
  {
    "filename": "b0512a575ab23533c5115454faa87d5b.jpg",
    "url": "/images/gallery/photography/b0512a575ab23533c5115454faa87d5b.jpg",
    "size": 4548852,
    "uploadedAt": "2026-06-02T12:55:16.293Z",
    "category": "摄影"
  },
  {
    "filename": "612576a26d5b9b9500d76c1ff9b9fd01.jpg",
    "url": "/images/gallery/photography/612576a26d5b9b9500d76c1ff9b9fd01.jpg",
    "size": 4865991,
    "uploadedAt": "2026-06-02T12:46:46.485Z",
    "category": "摄影"
  },
  {
    "filename": "91a3562b0e8e01341f2f619f6764b612.jpg",
    "url": "/images/gallery/photography/91a3562b0e8e01341f2f619f6764b612.jpg",
    "size": 5449831,
    "uploadedAt": "2026-06-02T12:44:00.653Z",
    "category": "摄影"
  },
  {
    "filename": "9890536476b75f59906c9ca3318704a4.jpg",
    "url": "/images/gallery/photography/9890536476b75f59906c9ca3318704a4.jpg",
    "size": 4215938,
    "uploadedAt": "2026-06-02T12:40:03.713Z",
    "category": "摄影"
  },
  {
    "filename": "a060217c1b1708ef976c5765dfb24489.jpg",
    "url": "/images/gallery/photography/a060217c1b1708ef976c5765dfb24489.jpg",
    "size": 7784296,
    "uploadedAt": "2026-06-02T12:37:46.472Z",
    "category": "摄影"
  },
  {
    "filename": "a67034eed338a00738f3af5da1612b8e.jpg",
    "url": "/images/gallery/photography/a67034eed338a00738f3af5da1612b8e.jpg",
    "size": 7209890,
    "uploadedAt": "2026-06-02T12:34:00.126Z",
    "category": "摄影"
  },
  {
    "filename": "66aad7e982aac7126750e155d0ff1918.jpg",
    "url": "/images/gallery/photography/66aad7e982aac7126750e155d0ff1918.jpg",
    "size": 5142094,
    "uploadedAt": "2026-06-02T12:33:08.955Z",
    "category": "摄影"
  },
  {
    "filename": "7f4471ec3b63306552c054da51dfe1d4.jpg",
    "url": "/images/gallery/photography/7f4471ec3b63306552c054da51dfe1d4.jpg",
    "size": 5967759,
    "uploadedAt": "2026-06-02T12:30:56.096Z",
    "category": "摄影"
  },
  {
    "filename": "c7b8adaf05d596ad59d89ee063789d1e.jpg",
    "url": "/images/gallery/photography/c7b8adaf05d596ad59d89ee063789d1e.jpg",
    "size": 4263073,
    "uploadedAt": "2026-06-02T12:30:21.669Z",
    "category": "摄影"
  },
  {
    "filename": "3a05ebcabd76005fe9d8e8a9a6978f03.jpg",
    "url": "/images/gallery/photography/3a05ebcabd76005fe9d8e8a9a6978f03.jpg",
    "size": 3399862,
    "uploadedAt": "2026-06-02T12:27:52.259Z",
    "category": "摄影"
  },
  {
    "filename": "fae36d2bd1733c1e4936654875d2f1d4.jpg",
    "url": "/images/gallery/photography/fae36d2bd1733c1e4936654875d2f1d4.jpg",
    "size": 3429773,
    "uploadedAt": "2026-06-02T12:25:58.729Z",
    "category": "摄影"
  },
  {
    "filename": "4e44c9b0677267d8585bff119f522b83.jpg",
    "url": "/images/gallery/photography/4e44c9b0677267d8585bff119f522b83.jpg",
    "size": 6281630,
    "uploadedAt": "2026-06-02T12:24:02.735Z",
    "category": "摄影"
  },
  {
    "filename": "b933a69c40fd07066c025e3e7eb3a940.jpg",
    "url": "/images/gallery/photography/b933a69c40fd07066c025e3e7eb3a940.jpg",
    "size": 4566850,
    "uploadedAt": "2026-06-02T12:20:58.890Z",
    "category": "摄影"
  },
  {
    "filename": "d4fb8e6790701d7ff93a2e291263336c.jpg",
    "url": "/images/gallery/photography/d4fb8e6790701d7ff93a2e291263336c.jpg",
    "size": 2753175,
    "uploadedAt": "2026-06-02T12:20:57.316Z",
    "category": "摄影"
  },
  {
    "filename": "fc5d0e2953bfcda203520ed5ee73b8f5.jpg",
    "url": "/images/gallery/photography/fc5d0e2953bfcda203520ed5ee73b8f5.jpg",
    "size": 2619030,
    "uploadedAt": "2026-06-02T12:19:18.294Z",
    "category": "摄影"
  },
  {
    "filename": "ebdbf9d678513efd46b724f0757c954f.jpg",
    "url": "/images/gallery/photography/ebdbf9d678513efd46b724f0757c954f.jpg",
    "size": 3008849,
    "uploadedAt": "2026-06-02T12:17:50.938Z",
    "category": "摄影"
  },
  {
    "filename": "3777bda65ff5e3ae31e9c2e50280b8d4.jpg",
    "url": "/images/gallery/photography/3777bda65ff5e3ae31e9c2e50280b8d4.jpg",
    "size": 9701982,
    "uploadedAt": "2026-06-02T12:17:49.204Z",
    "category": "摄影"
  },
  {
    "filename": "cover.jpg",
    "url": "/images/gallery/travel/cover.jpg",
    "size": 1282241,
    "uploadedAt": "2026-06-02T11:55:48.097Z",
    "category": "旅行"
  },
  {
    "filename": "672752cda3c571f958cfeb62e8a1cb93.jpg",
    "url": "/images/gallery/travel/672752cda3c571f958cfeb62e8a1cb93.jpg",
    "size": 348616,
    "uploadedAt": "2026-06-02T11:55:37.140Z",
    "category": "旅行"
  },
  {
    "filename": "f87ee0654ade57e828dd439c30ad39b4.jpg",
    "url": "/images/gallery/travel/f87ee0654ade57e828dd439c30ad39b4.jpg",
    "size": 539487,
    "uploadedAt": "2026-06-02T11:55:36.253Z",
    "category": "旅行"
  },
  {
    "filename": "bfe5548a72463266a86d1218fef8421c.jpg",
    "url": "/images/gallery/travel/bfe5548a72463266a86d1218fef8421c.jpg",
    "size": 889423,
    "uploadedAt": "2026-06-02T11:55:35.180Z",
    "category": "旅行"
  },
  {
    "filename": "ed690ee56defc441a4a1b63d218443b9.jpg",
    "url": "/images/gallery/travel/ed690ee56defc441a4a1b63d218443b9.jpg",
    "size": 386915,
    "uploadedAt": "2026-06-02T11:55:04.922Z",
    "category": "旅行"
  },
  {
    "filename": "895b21bbd37ac46736d59428ec6ea00e.jpg",
    "url": "/images/gallery/travel/895b21bbd37ac46736d59428ec6ea00e.jpg",
    "size": 1052701,
    "uploadedAt": "2026-06-02T11:54:53.805Z",
    "category": "旅行"
  },
  {
    "filename": "5e86c591333f3f4e3cffd24273489feb.jpg",
    "url": "/images/gallery/travel/5e86c591333f3f4e3cffd24273489feb.jpg",
    "size": 1667695,
    "uploadedAt": "2026-06-02T11:54:23.671Z",
    "category": "旅行"
  },
  {
    "filename": "4e337a53c5e4ff883adb8ce926fa1950.jpg",
    "url": "/images/gallery/travel/4e337a53c5e4ff883adb8ce926fa1950.jpg",
    "size": 1214957,
    "uploadedAt": "2026-06-02T11:53:57.601Z",
    "category": "旅行"
  },
  {
    "filename": "7e812ac33c4ee0d0e757abdc3020a9dc.jpg",
    "url": "/images/gallery/travel/7e812ac33c4ee0d0e757abdc3020a9dc.jpg",
    "size": 226405,
    "uploadedAt": "2026-06-02T11:52:59.348Z",
    "category": "旅行"
  },
  {
    "filename": "e78c1f536e7195181c3cccb8820949f5.jpg",
    "url": "/images/gallery/travel/e78c1f536e7195181c3cccb8820949f5.jpg",
    "size": 109842,
    "uploadedAt": "2026-06-02T11:52:56.730Z",
    "category": "旅行"
  },
  {
    "filename": "c208387f6043e58e6a386b636f9b4db5.jpg",
    "url": "/images/gallery/travel/c208387f6043e58e6a386b636f9b4db5.jpg",
    "size": 187995,
    "uploadedAt": "2026-06-02T11:52:55.620Z",
    "category": "旅行"
  },
  {
    "filename": "740de3ffac42a715ab06ceb90d0190e4.jpg",
    "url": "/images/gallery/travel/740de3ffac42a715ab06ceb90d0190e4.jpg",
    "size": 296336,
    "uploadedAt": "2026-06-02T11:52:54.218Z",
    "category": "旅行"
  },
  {
    "filename": "f6e9bf22d56eac12a854f8b784a1a9f6.jpg",
    "url": "/images/gallery/travel/f6e9bf22d56eac12a854f8b784a1a9f6.jpg",
    "size": 420575,
    "uploadedAt": "2026-06-02T11:52:49.680Z",
    "category": "旅行"
  },
  {
    "filename": "be5ad060a581a35dce2ba57fdeeae592.jpg",
    "url": "/images/gallery/travel/be5ad060a581a35dce2ba57fdeeae592.jpg",
    "size": 308232,
    "uploadedAt": "2026-06-02T11:52:18.627Z",
    "category": "旅行"
  },
  {
    "filename": "c6dee8bec6f73112de54d70868aa7e55.jpg",
    "url": "/images/gallery/travel/c6dee8bec6f73112de54d70868aa7e55.jpg",
    "size": 147080,
    "uploadedAt": "2026-06-02T11:52:12.820Z",
    "category": "旅行"
  },
  {
    "filename": "c6121b3bb74e2c075f6ff2719ee9776c.jpg",
    "url": "/images/gallery/travel/c6121b3bb74e2c075f6ff2719ee9776c.jpg",
    "size": 855240,
    "uploadedAt": "2026-06-02T11:52:09.992Z",
    "category": "旅行"
  },
  {
    "filename": "c5f0d3346605a2644b9c54761e7f5221.jpg",
    "url": "/images/gallery/travel/c5f0d3346605a2644b9c54761e7f5221.jpg",
    "size": 718526,
    "uploadedAt": "2026-06-02T11:51:45.040Z",
    "category": "旅行"
  },
  {
    "filename": "7d173721f8339883fa6de516c2714c5c.jpg",
    "url": "/images/gallery/travel/7d173721f8339883fa6de516c2714c5c.jpg",
    "size": 447471,
    "uploadedAt": "2026-06-02T11:51:28.034Z",
    "category": "旅行"
  },
  {
    "filename": "3b2f22ba54920e2284bf768674dcab72.jpg",
    "url": "/images/gallery/travel/3b2f22ba54920e2284bf768674dcab72.jpg",
    "size": 1500452,
    "uploadedAt": "2026-06-02T11:51:09.194Z",
    "category": "旅行"
  },
  {
    "filename": "18a20284797a1eb56f22e56fa2cf1e89.jpg",
    "url": "/images/gallery/travel/18a20284797a1eb56f22e56fa2cf1e89.jpg",
    "size": 625138,
    "uploadedAt": "2026-06-02T11:50:14.755Z",
    "category": "旅行"
  },
  {
    "filename": "ca1bffd840009edf710955818b6774ae.jpg",
    "url": "/images/gallery/travel/ca1bffd840009edf710955818b6774ae.jpg",
    "size": 502415,
    "uploadedAt": "2026-06-02T11:50:10.221Z",
    "category": "旅行"
  },
  {
    "filename": "b7cb21882701c5f4e41da4359a36b559.jpg",
    "url": "/images/gallery/travel/b7cb21882701c5f4e41da4359a36b559.jpg",
    "size": 658460,
    "uploadedAt": "2026-06-02T11:50:01.038Z",
    "category": "旅行"
  },
  {
    "filename": "78fd673ca2c2bfe64f114fc61d17358e.jpg",
    "url": "/images/gallery/travel/78fd673ca2c2bfe64f114fc61d17358e.jpg",
    "size": 1282241,
    "uploadedAt": "2026-06-02T11:44:54.946Z",
    "category": "旅行"
  },
  {
    "filename": "cover.jpg",
    "url": "/images/gallery/campus/cover.jpg",
    "size": 2715095,
    "uploadedAt": "2026-06-02T11:22:16.869Z",
    "category": "校园"
  },
  {
    "filename": "b00633153f6af498464f9a6e83c43f1f.jpg",
    "url": "/images/gallery/campus/b00633153f6af498464f9a6e83c43f1f.jpg",
    "size": 4634244,
    "uploadedAt": "2026-06-02T11:22:01.773Z",
    "category": "校园"
  },
  {
    "filename": "1f20fee7ae6800ee5fc705a395cf018d.jpg",
    "url": "/images/gallery/campus/1f20fee7ae6800ee5fc705a395cf018d.jpg",
    "size": 6060408,
    "uploadedAt": "2026-06-02T11:18:59.494Z",
    "category": "校园"
  },
  {
    "filename": "8a7cf2dd9f8495735aa24883bfcad13b.jpg",
    "url": "/images/gallery/campus/8a7cf2dd9f8495735aa24883bfcad13b.jpg",
    "size": 3835752,
    "uploadedAt": "2026-06-02T11:15:03.527Z",
    "category": "校园"
  },
  {
    "filename": "890838c56c373ccf39382145b79cd17c.jpg",
    "url": "/images/gallery/campus/890838c56c373ccf39382145b79cd17c.jpg",
    "size": 2767510,
    "uploadedAt": "2026-06-02T11:08:14.700Z",
    "category": "校园"
  },
  {
    "filename": "37218c7c5728cf7aa02a3d3ec01cea24.jpg",
    "url": "/images/gallery/campus/37218c7c5728cf7aa02a3d3ec01cea24.jpg",
    "size": 4676409,
    "uploadedAt": "2026-06-02T11:06:42.142Z",
    "category": "校园"
  },
  {
    "filename": "248ff128d150d3a552ee9270734a1e38.jpg",
    "url": "/images/gallery/campus/248ff128d150d3a552ee9270734a1e38.jpg",
    "size": 2715095,
    "uploadedAt": "2026-06-02T11:02:29.755Z",
    "category": "校园"
  },
  {
    "filename": "97e2d4b849dcf3b7b842dad2cb7991f6.jpg",
    "url": "/images/gallery/campus/97e2d4b849dcf3b7b842dad2cb7991f6.jpg",
    "size": 4385924,
    "uploadedAt": "2026-06-02T11:00:38.963Z",
    "category": "校园"
  },
  {
    "filename": "60e81f7160463c8a154afbaf2fbea9cd.jpg",
    "url": "/images/gallery/campus/60e81f7160463c8a154afbaf2fbea9cd.jpg",
    "size": 6228245,
    "uploadedAt": "2026-06-02T10:56:49.751Z",
    "category": "校园"
  },
  {
    "filename": "sample.svg",
    "url": "/images/gallery/sample.svg",
    "size": 625,
    "uploadedAt": "2026-06-01T11:48:03.847Z"
  }
];

// ─── Data Files ────────────────────────────────────────────────────
export const friends: Friend[] = [
  {
    "name": "Shaoguang369",
    "url": "https://shaoguang369.top/",
    "avatar": "https://raw.githubusercontent.com/Nofear0304/image/master/photo/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202026-06-02%20213659.png",
    "description": "一位有趣的技术博主"
  }
];

export const initialLikesData: { articles: Record<string, number>; notes: Record<string, number> } = {
  "articles": {},
  "notes": {
    "code-refactoring": 3
  }
};

export const initialCommentsData: ContentComment[] = [];

export const initialMessagesData: GuestbookMessage[] = [
  {
    "nickname": "Liberty",
    "content": "希望大家给我提出建议，也欢迎互相分享自己的网站",
    "id": "mpwobvxzkmni18",
    "createdAt": "2026-06-02T13:29:11.543Z",
    "likes": 1
  }
];

export const initialVisitsData: { count: number; daily: Record<string, number> } = {
  "count": 0,
  "daily": {}
};
